
library(drake)
library(googledrive)
library(googlesheets4)
library(raster)
library(geosphere)
library(gdistance)
library(windscape)
library(diveRsity)
library(doParallel)
library(hierfstat)
library(diveRsity)
library(tidyverse)
library(taxize)
library(furrr)
library(patchwork)


library(conflicted)
conflict_prefer("select", "dplyr", quiet = T)
conflict_prefer("filter", "dplyr", quiet = T)
conflict_prefer("gather", "tidyr", quiet = T)
conflict_prefer("extract", "raster", quiet = T)
conflict_prefer("lag", "dplyr", quiet = T)
conflict_prefer("values", "raster", quiet = T) 
conflict_prefer("setdiff", "base", quiet = T) 
conflict_prefer("annotate", "ggplot2", "patchwork", quiet = T) 
